#!/bin/bash
# Generates docker-compose.override.yml so the Jekyll container can see this
# checkout's real .git directory.
#
# git worktrees only contain a `.git` *file* pointing at an absolute path
# inside the main repo's `.git/worktrees/<name>` directory. docker-compose.yml
# only bind-mounts this checkout, so that path doesn't exist in the
# container and any git command (e.g. jekyll-github-metadata) fails with
# "fatal: not a git repository". Bind-mounting the common .git dir at the
# same absolute path fixes it, but that path is different on every machine
# and worktree, so it can't be hardcoded into the committed docker-compose.yml.
#
# Run this once per worktree checkout (and again if the worktree is moved).
# Plain (non-worktree) checkouts don't need this — no override is created.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

git_dir=$(git rev-parse --path-format=absolute --git-dir)
common_dir=$(git rev-parse --path-format=absolute --git-common-dir)

if [ "$git_dir" = "$common_dir" ]; then
  echo "Not a linked worktree; no override needed."
  rm -f docker-compose.override.yml
  exit 0
fi

cat > docker-compose.override.yml <<EOF
# Generated by docker-worktree-setup.sh — do not commit (see .gitignore).
services:
  jekyll:
    volumes:
      - ${common_dir}:${common_dir}:rw
EOF

echo "Wrote docker-compose.override.yml mounting ${common_dir}"
